modLoader = "javafml"
loaderVersion = "[4,)"
license="GNU LGLP3"

[properties]
"connector:placeholder"=true

[[mods]]
modId="lightwithin"
version="1.2.0+1.21.1"
displayName="LightWithin"
authors="Emafire003"
description='''Adding new fancy magical-ish and player-unique powers, the 'InnerLights' which are going to activate when the player is in danger!'''

[[dependencies.lightwithin]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lightwithin]]
modId="minecraft"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.lightwithin]]
modId="connector"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.lightwithin]]
modId="velvet-api"
mandatory=true
versionRange="*"
ordering="NONE"
side="CLIENT"

[[dependencies.lightwithin]]
modId="custumbrewrecipes"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"